### ISSUE TITLE
Updating a deployment fails at update_lambda_configuration

### ISSUE THREAD

**Issue by mdunc** [zappa/Zappa#1035]
Updating a deployment fails at update_lambda_configuration due to a KeyError
## Context
I've had no problems updating this deployment until today.  Python version is 3.8.10. 

## Expected Behavior
Zappa should complete the update of the deployment successfully.

## Actual Behavior
Zappa fails with the following output:
```
$ zappa update prod
Calling update for stage prod..
Downloading and installing dependencies..
 - pyyaml==5.4.1: Downloading
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 662k/662k [00:00<00:00, 6.57MB/s]
Packaging project as zip.
Uploading tellya2-prod-1631583880.zip (21.9MiB)..
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 23.0M/23.0M [00:04<00:00, 4.86MB/s]
Updating Lambda function code..
Updating Lambda function configuration..
Oh no! An error occurred! :(

==============

Traceback (most recent call last):
  File "/Users/mark/.virtualenvs/tellya2_project/lib/python3.8/site-packages/zappa/cli.py", line 3422, in handle
    sys.exit(cli.handle())
  File "/Users/mark/.virtualenvs/tellya2_project/lib/python3.8/site-packages/zappa/cli.py", line 588, in handle
    self.dispatch_command(self.command, stage)
  File "/Users/mark/.virtualenvs/tellya2_project/lib/python3.8/site-packages/zappa/cli.py", line 641, in dispatch_command
    self.update(
  File "/Users/mark/.virtualenvs/tellya2_project/lib/python3.8/site-packages/zappa/cli.py", line 1165, in update
    self.lambda_arn = self.zappa.update_lambda_configuration(
  File "/Users/mark/.virtualenvs/tellya2_project/lib/python3.8/site-packages/zappa/core.py", line 1395, in update_lambda_configuration
    if lambda_aws_config["PackageType"] != "Image":
KeyError: 'PackageType'

==============

Need help? Found a bug? Let us know! :D
File bug reports on GitHub here: https://github.com/Zappa/Zappa
And join our Slack channel here: https://zappateam.slack.com
Love!,
 ~ Team Zappa!
```

## Possible Fix
None that I'm aware of.

## Steps to Reproduce
Unfortunately this is a private code repository so I cannot provide any links.  

## Your Environment
* Zappa version used: 0.53.0
* Operating System and Python version: MacOS 11.5.1 - Python 3.8.10
* The output of `pip freeze`:
argcomplete==1.12.3
asgiref==3.3.4
boto3==1.17.97
botocore==1.20.97
certifi==2021.5.30
cfn-flip==1.2.3
chardet==4.0.0
click==8.0.1
Django==3.2.4
django-appconf==1.0.4
django-compressor @ git+https://github.com/django-compressor/django-compressor.git@f533dc6dde9ed90626382d78f3eb37b84d848027
django-formtools==2.3
django-libsass==0.9
django-otp==1.0.6
django-phonenumber-field==5.2.0
django-storages==1.11.1
django-tenants==3.3.1
django-two-factor-auth==1.13.1
durationpy==0.5
future==0.18.2
hjson==3.0.2
idna==2.10
jmespath==0.10.0
kappa==0.6.0
libsass==0.21.0
pbr==5.6.0
pep517==0.10.0
phonenumbers==8.12.25
pip-tools==6.1.0
placebo==0.9.0
psycopg2==2.9.1
psycopg2-binary==2.9.1
PyJWT==1.7.1
python-dateutil==2.8.1
python-slugify==5.0.2
pytz==2021.1
PyYAML==5.4.1
qrcode==6.1
rcssmin==1.0.6
requests==2.25.1
rjsmin==1.1.0
s3transfer==0.4.2
six==1.15.0
sqlparse==0.4.1
stevedore==3.3.0
text-unidecode==1.3
toml==0.10.2
tqdm==4.61.1
troposphere==2.7.0
twilio==6.61.0
urllib3==1.26.5
Werkzeug==0.16.1
wsgi-request-logger==0.4.6
zappa==0.53.0
zappa-django-utils==0.4.1
* Your `zappa_settings.json`: 
```
{
    "dev": {
        "aws_region": "ap-northeast-1",
        "django_settings": "config.settings.dev",
        "profile_name": "default",
        "project_name": "tellya2",
        "runtime": "python3.8",
        "s3_bucket": "tellya2-dev",
        "keep_warm": false,
        "vpc_config": {
            "SubnetIds": ["subnet-085938da970945e07"],
            "SecurityGroupIds": ["sg-0353477a152c17539"]
        },
        "layers": ["arn:aws:lambda:ap-northeast-1:898466741470:layer:psycopg2-py38:1"],
        "delete_local_zip": true,
        "exclude": ["static", "psycopg2", "*.pyc", "pip", "pip-tools", "setuptools", "*.dist-info", "*.so"],
        "events": [{
            "function": "tellya2.lambda_functions.check_messages", 
            "expression": "rate(1 minute)"
        }]
    },
    "prod": {
        "aws_region": "ap-northeast-1",
        "django_settings": "config.settings.prod",
        "profile_name": "default",
        "project_name": "tellya2",
        "runtime": "python3.8",
        "s3_bucket": "tellya2-prod",
        "keep_warm": true,
        "vpc_config": {
            "SubnetIds": ["subnet-0042d4fa27f9253ae", "subnet-0768c029b7e2d32c3"],
            "SecurityGroupIds": ["sg-446b8d00"]
        },
        "layers": ["arn:aws:lambda:ap-northeast-1:898466741470:layer:psycopg2-py38:1"],
        "delete_local_zip": true,
        "exclude": ["static", "psycopg2", "pip*", "pip-tools*", "setuptools", "*.pyc", "*.dist-info", "*.so"],
        "events": [{
            "function": "tellya2.lambda_functions.check_messages", 
            "expression": "rate(1 minute)"
        }],
        "certificate_arn": "arn:aws:acm:us-east-1:214849182730:certificate/19237cc2-0571-4045-bc10-face4e581f3d",
        "domain": "[redacted]"
    }
}
```

**Comment by mdunc** [comment]
Side note - I tried to join the Slack channel given in the output, but it does not actually seem possible to join it.  Perhaps that message should be removed?

**Comment by mdunc** [comment]
The zip file does get uploaded to S3 and the Lambda function does appear to get updated so I can at least make _some_ updates, but that's as far as it gets.  It doesn't appear to reschedule tasks or verify if the deployments was successful.

**Comment by ivanst-stoyanov** [comment]
Yesterday I noticed the same issue. I am able to deploy the lambda but when I try to update it this pops up.
I checked Zappa's code and it is getting the lambda config from AWS and then looking for a `PackageType` property in that config which now is missing.
I thing AWS changed something and this property is no longer returned with the config.

I am hoping that this will be resolved quickly.

**Comment by klorophyl** [comment]
Same here :/ the code is updated though

**Comment by antoinepay** [comment]
Same here

**Comment by marcocarranza** [comment]
Got the same problem. The code is updated i just validated many times. Yesterday i manually added to the Lambda, through AWS website, a Lambda Layer with wkhtmltopdf from this link. Probably the extra layer generate the conflict.

https://wkhtmltopdf.org/downloads.html

**Comment by ivanst-stoyanov** [comment]
> Got the same problem. The code is updated i just validated many times. Yesterday i manually added to the Lambda, through AWS website, a Lambda Layer with wkhtmltopdf from this link. Probably the extra layer generate the conflict.
> 
> [wkhtmltopdf.org/downloads.html](https://wkhtmltopdf.org/downloads.html)

I have added a layer to my lambda as well. It is added to the `layers` property in the `zappa_settings.json` file and I have had no problems with it until now.

I can also confirm that the code is deployed, however my AWS CodePipeline build fails because of the error and I have to run the DB migrations manually from my machine.

**Comment by jumprope-jesse** [comment]
I'm seeing the same error as well.  Started this morning after no configuration changes since last deployment (worked yesterday with code & dependencies). I do use layers + a fairly large deployment package (but under 50mb so not via S3).  FWIW I am able to workaround with a couple of small modifications to zappa/core.py but it's too hackish to offer as a pull request.

**Comment by javulticat** [comment]
I opened a PR to fix this here: #1042 

Details are in the PR description, but the TL;DR is that the code currently assumes that the Lambda function is fully initialized at this point, but if it isn't, the response will *not* contain the `PackageType` key.  AWS (at least `us-east-1`) seems to be suffering some kind of performance degradation where the Lambda function is frequently not initialized in time.

**Comment by jumprope-jesse** [comment]
@javulticat agreed - my workaround was the same idea (wait loop with sleep) but sloppier.  AWS isn't reporting anything, but it looks to me like lambda "updates" via the api call are taking ~30 seconds when they usually take ~1 second.  Thanks for the PR

**Comment by cwaldbieser** [comment]
I can confirm that I experienced the same symptoms.  I have an app with a Lambda layer.  No changes to configuration.  Tried to update application code.  Stack trace with KeyError: 'PackageType'.

I applied the PR from @javulticat to my own forked version of Zappa.  Now when I update it does wait a little longer, but it is successful.  Thanks, @javulticat !

**Comment by mdunc** [comment]
I see that Zappa has been officially suddenly deprecated without warning in the most recent commits.  That's a real shame.

**Comment by klorophyl** [comment]
Well this is bad ..

**Comment by ivanst-stoyanov** [comment]
Is there any plan for merging the fix in this repo?

**Comment by javulticat** [comment]
Resolved as of `v0.54.0` via #992

**Comment by lucas-sorrentino** [comment]
Hi there,

so, I run into the same problem, and updaredmy zappa to version 0.54.1, but the error persists. 
Someone know what could be still causing it?

I have other environment using zappa, and updating it resolve the problem. The only diference between the two is the python version. 

Using 3.8.4, the problem is solved. Using 3.7.6, the problem persists.

I am missing something here?

**Comment by navdeep710** [comment]
have pushed in quick fix in 
https://github.com/zappa/Zappa/pull/1108

**Comment by hamzach** [comment]
I was facing same issue, I uninstalled and reinstalled the updated package. Problem is resolved now.

**Comment by ohadbenita** [comment]
> I was facing same issue, I uninstalled and reinstalled the updated package. Problem is resolved now.

Can you expand on how did you uninstalled / reinstalled the package? What package are you referring to?

**Comment by hamzach** [comment]
> > I was facing same issue, I uninstalled and reinstalled the updated package. Problem is resolved now.
> 
> Can you expand on how did you uninstalled / reinstalled the package? What package are you referring to?

My problem was solved with latest  version.

Simply run:
`pip uninstall zappa`
and then
`pip install zappa`
It will install the latest version.

**Comment by ohadbenita** [comment]
We install our dependencies in a fresh docker container so that didn't help, thanks though.
What I did notice is that it only happens for us in one of 6 regions we're deployed in.

**Comment by ladyshaitan** [comment]
@ohadbenita This is happening to me as well in `us-east-1`, can you list out which regions you're noticing this issue with?  This is an ongoing issue for me on version `0.54.1` on a fresh install.

**Comment by ohadbenita** [comment]
Same here, only `us-east-1`, all other regions (`us-west-2`, `eu-central-1`, `eu-west-1`...) don't have this issue. I've been in contact with AWS support about this to rule out an API issue but the same API call succeeds using the AWS CLI. The only thing left to be done is print the actual API call made by Zappa to `UpdateFunctionConfiguration` to be able to continue the thread with AWS support.
